version: "3.9"

networks:
  default:
    name: 'ems-network'

services:
  service-debug-service-access-handler:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    logging:
      options:
        max-size: '50M'
        max-file: '5'
    ulimits:
      core:
        hard: 0
        soft: 0
    hostname: service-debug-service-access-handler
    environment:
      ServicePort: :8080
    deploy:
      resources:
        limits:
          cpus: "3"
          memory: 2000M
        reservations:
          cpus: "0.5"
          memory: 400M